name: Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        uses: borales/actions-yarn@v4
        with:
          cmd: install # `yarn install`

      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test # `yarn test`